youwe_file_manager_list:
    resource: "@YouweFileManagerBundle/Controller/"
    type:     annotation
    prefix:   /media

youwe_uploads:
    pattern: /uploads/{name}
    requirements:
        name: .+
    defaults:
        _controller: YouweFileManagerBundle:Security:security