services:
  youwe.file_manager.service:
    class: Youwe\FileManagerBundle\Services\FileManagerService
    arguments: ["@service_container"]
  youwe.file_manager.driver:
    class: Youwe\FileManagerBundle\Driver\FileManagerDriver
    arguments: ["@service_container"]